apiVersion: v1
kind: Service
metadata:
  name: companyservice
  namespace: jobportal
  labels:
    app: companyservice
spec:
  selector:
    app: companyservice
  ports:
    - name: company
      port: 9003
      targetPort: company
  type: ClusterIP

