apiVersion: v1
kind: Service
metadata:
  name: cvservice
  namespace: jobportal
  labels:
    app: cvservice
spec:
  selector:
    app: cvservice
  ports:
    - name: cv
      port: 8086
      targetPort: cv
  type: ClusterIP


