apiVersion: v1
kind: Service
metadata:
  name: jobservice
  namespace: jobportal
  labels:
    app: jobservice
spec:
  selector:
    app: jobservice
  ports:
  - name: job
    port: 9001
    targetPort: job
  type: ClusterIP






