apiVersion: v1
kind: Service
metadata:
  name: jobapplicationservice
  namespace: jobportal
  labels:
    app: jobapplicationservice
spec:
  selector:
    app: jobapplicationservice
  ports:
    - name: jobapp
      port: 9002
      targetPort: jobapp
  type: LoadBalancer


