apiVersion: v1
kind: Service
metadata:
  name: jobseekerservice
  namespace: jobportal
  labels:
    app: jobseekerservice
spec:
  selector:
    app: jobseekerservice
  ports:
    - name: jobseeker
      port: 8085
      targetPort: jobseeker
  type: ClusterIP


