# mysql-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: sql
data:
  my.cnf: |
    [mysqld]
    bind-address=0.0.0.0
    sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
