apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "aaa123"
            - name: MYSQL_DATABASE
              value: "jobseeker"
            - name: MYSQL_USER
              value: "abdullah"
            - name: MYSQL_PASSWORD
              value: "aaa123"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-config-volume
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
      volumes:
        - name: mysql-storage
          emptyDir: {}
        - name: mysql-config-volume
          configMap:
            name: mysql-config
