apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  namespace: jobportal
  labels:
    app: configserver 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: configserver
    spec:
      hostAliases:
      - ip: "172.25.1.140"
        hostnames:
        - "git.hiast.edu.sy"
      containers:
        - name: configserver
          image: 172.29.3.41:5000/configserver:1.0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "700Mi"
              cpu: "400m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: companyservice
  namespace: jobportal
  labels:
    app: companyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: companyservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: companyservice
    spec:
      containers:
        - name: companyservice
          image: 172.29.3.41:5000/companysvc:1.0.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: company
              containerPort: 9003
          volumeMounts:
            - name: company-images
              mountPath: /app/src/main/resources/images
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "700Mi"
              cpu: "400m"
      volumes:
        - name: company-images
          persistentVolumeClaim:
            claimName: companyservice-images
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvservice
  namespace: jobportal
  labels:
    app: cvservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cvservice
    spec:
      containers:
        - name: cvservice
          image: 172.29.3.41:5000/cvservice:1.0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: cv
              containerPort: 8086
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "700Mi"
              cpu: "400m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayservice
  namespace: jobportal
  labels:
    app: gatewayservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gatewayservice
    spec:
      containers:
        - name: gatewayservice
          image: 172.29.3.41:5000/gatewaysvc:1.0.0.10
          imagePullPolicy: IfNotPresent
          ports:
            - name: gate
              containerPort: 8000
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1000Mi"
              cpu: "600m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interviewservice
  namespace: jobportal
  labels:
    app: interviewservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interviewservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: interviewservice
    spec:
      containers:
        - name: interviewservice
          image: 172.29.3.41:5000/interviewsvc:1.0.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: interview
              containerPort: 8087
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "700Mi"
              cpu: "400m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobservice
  namespace: jobportal
  labels:
    app: jobservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jobservice
    spec:
      containers:
        - name: jobservice
          image: 172.29.3.41:5000/jobsvc:1.0.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: job
              containerPort: 9001
          resources:
            requests:
              memory: "400Mi"
              cpu: "200m"
            limits:
              memory: "850Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobapplicationservice
  namespace: jobportal
  labels:
    app: jobapplicationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobapplicationservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jobapplicationservice
    spec:
      containers:
        - name: jobapplicationservice
          image: 172.29.3.41:5000/jobapplication:1.0.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: jobapp
              containerPort: 9002
          resources:
            requests:
              memory: "400Mi"
              cpu: "200m"
            limits:
              memory: "850Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobseekerservice
  namespace: jobportal
  labels:
    app: jobseekerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobseekerservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jobseekerservice
    spec:
      containers:
        - name: jobseekerservice
          image: 172.29.3.41:5000/jobseekersvc:1.0.0.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: jobseeker
              containerPort: 8085
          volumeMounts:
            - name: jobseeker-images
              mountPath: /app/src/main/resources/images
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "700Mi"
              cpu: "400m"
      volumes:
        - name: jobseeker-images
          persistentVolumeClaim:
            claimName: jobseekerservice-images
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationservice
  namespace: jobportal
  labels:
    app: notificationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notificationservice
    spec:
      containers:
        - name: notificationserver
          image: 172.29.3.41:5000/notificationsvc:1.0.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: notification
              containerPort: 8090
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "700Mi"
              cpu: "400m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequenceservice
  namespace: jobportal
  labels:
    app: sequenceservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sequenceservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sequenceservice
    spec:
      containers:
        - name: sequenceservice
          image: 172.29.3.41:5000/sequencegenerator:1.0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: sequence
              containerPort: 9000
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "700Mi"
              cpu: "400m"
