apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: jobportal
spec:
  containers:
  - name: curl-container
    image: curlimages/curl
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    - sleep infinity