apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobservice
  namespace: jobportal
  labels:
    app: jobservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jobservice
    spec:
      containers:
        - name: jobservice
          image: 172.29.3.41:5000/jobsvc-prod:1.0.0.81
          imagePullPolicy: IfNotPresent
          ports:
            - name: job
              containerPort: 9001
