apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobapplicationservice
  namespace: jobportal
  labels:
    app: jobapplicationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobapplicationservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jobapplicationservice
    spec:
      containers:
        - name: jobapplicationservice
          image: 172.29.3.41:5000/jobapplication:1.0.0.11
          imagePullPolicy: IfNotPresent
          ports:
            - name: jobapp
              containerPort: 9002
