apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
            - name: mongodb-config-volume
              mountPath: /etc/mongo/mongod.conf
              subPath: mongod.conf
      volumes:
        - name: mongodb-storage
          emptyDir: {}
        - name: mongodb-config-volume
          configMap:
            name: mongodb-config
