# mongodb-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: mongo
data:
  mongod.conf: |
    # Custom MongoDB configuration
    storage:
      dbPath: /usr/local/mongodb/cv-mongo
    net:
      bindIp: 0.0.0.0
