apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jobapplication
  namespace: jobportal
  labels:
    app: prometheus
spec:
  endpoints:
  - interval: 30s
    port: jobapp
    path: /actuator/prometheus
  selector:
    matchLabels:
      app: jobapplicationservice
 
