apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification
  namespace: jobportal
  labels:
    app: prometheus
spec:
  endpoints:
  - interval: 30s
    port: notification
    path: /actuator/prometheus
  selector:
    matchLabels:
      app: notificationservice
 
