apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cv
  namespace: jobportal
  labels:
    app: prometheus
spec:
  endpoints:
  - interval: 30s
    port: cv
    path: /actuator/prometheus
  selector:
    matchLabels:
      app: cvservice
 
