apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: job
  namespace: jobportal
  labels:
    app: prometheus
spec:
  endpoints:
  - interval: 30s
    port: job
    path: /actuator/prometheus
  selector:
    matchLabels:
      app: jobservice
 
