apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sequencegenerator
  namespace: jobportal
  labels:
    app: prometheus
spec:
  endpoints:
  - interval: 30s
    port: sequence
    path: /actuator/prometheus
  selector:
    matchLabels:
      app: sequenceservice
 
